### ISSUE TITLE
yml line 28

### ISSUE THREAD

**Issue by jeringuilla02** [acocalypso/DiscordRoleManager#53]
I trying to Install it in docker and i get that Error in the Foto above i followed All the steps as i should 
![rn_image_picker_lib_temp_1ea44c7c-e232-4447-b612-a3806d8a7639](https://user-images.githubusercontent.com/35981041/197493669-390050ed-1eaa-457d-a21e-dd5aced5be98.jpg)
and nothing work.
How could we fix it

**Comment by acocalypso** [comment]
- have you cloned the repository?
- have you renamend docker-compose.yml.example to docker-compose.yml?

I just did a quick test and its working fine:

```
~/drm-test$ cp docker-compose.yml.example docker-compose.yml
~/drm-test$ docker-compose pull
[+] Running 8/8
 ⠿ discordrolebot Pulled                                                   8.0s
   ⠿ 213ec9aee27d Already exists                                           0.0s
   ⠿ 90d4f1a52341 Pull complete                                            3.2s
   ⠿ 96f9ff3b94d8 Pull complete                                            3.3s
   ⠿ f05a94b04b95 Pull complete                                            3.4s
   ⠿ 2d6f3a3f115d Pull complete                                            3.6s
   ⠿ 10d9929f4fd9 Pull complete                                            3.7s
   ⠿ a7369d5f19e7 Pull complete   

```

can you show me the docker-dompose file that you are using and which docker-compose version are you using?

docker-compose --version
Docker Compose version v2.4.1

**Comment by jeringuilla02** [comment]
i find a little error in "defaultDonatorRole": "1234567896548"
and it work with a coma like this
"defaultDonatorRole": "1234567896548",

[image: error.png]

Am Mo., 24. Okt. 2022 um 11:36 Uhr schrieb acocalypso <
***@***.***>:

**Comment by acocalypso** [comment]
Thanks fixed.

So can you tell me your steps to reproduce your issue?

**Comment by jeringuilla02** [comment]
It's Normal? I installed as docker i have three day with help from a friend
trying to geht it working and nothing happen. Few we installed and delete
with not Error in console but the command?register and all the other wont
work. Just ?map and ?check admin work with that one error.
What you think about it?
Thanks in advance 🙏

acocalypso ***@***.***> schrieb am Mo., 24. Okt. 2022, 18:42:

**Comment by acocalypso** [comment]
For further help, please provide log outputs from the log file and from docker-compose logs -f

**Comment by acocalypso** [comment]
can you  pull latest master and try it again?

**Comment by jeringuilla02** [comment]
Im on the way to install it in a vm just one error dependecy discord.js
the docker hasnt logs to see i uninstalled it for a while.

acocalypso ***@***.***> schrieb am Do., 27. Okt. 2022, 23:06:

**Comment by jeringuilla02** [comment]
Im in anydesk right now i wait of you If you want

acocalypso ***@***.***> schrieb am Di., 1. Nov. 2022, 19:41:
