### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by jeringuilla02** [acocalypso/DiscordRoleManager#54]
I got Always the error you have no permission to run these command or you are not allowed to run that command because your @username are not in Database Name.
or i couldn't add my user to the adminrole.
How I do u fixed...
First. I created an discord a role and i called it admin, i add my discord username to that role.
![Screenshot_2022-11-01-11-07-14-597_com discord-edit](https://user-images.githubusercontent.com/35981041/199209994-9f1350b6-ee4b-4b3c-b814-7484d06cb64e.jpg)
 Then i change in DRM config file the ownerid for the admin role id that i created and restart the docker.
Now on discord i (prefix)register adminrole @AdminRole where @AdminRole ist the admin role that i created in discord.
Than i followed the DRM guide as normal.

**Comment by acocalypso** [comment]
First the role name must be @rolename or leave it if you defined a default role in config.

The owner ID must be a user ID not a role ID

**Comment by jeringuilla02** [comment]
I know it's in the guide but nothing was working.
Now work like a charm

acocalypso ***@***.***> schrieb am Di., 1. Nov. 2022, 12:18:

**Comment by jeringuilla02** [comment]
In show you my setting when i get home

Ruperto Camarena ***@***.***> schrieb am Di., 1. Nov. 2022,
12:41:

**Comment by jeringuilla02** [comment]
if you have anydesk i leave you see what i meant or i invite you to my
discord server channel

anydesk 772 375 935
password LosHuevos2020

discord
https://discord.gg/EzwjK5nn

Am Di., 1. Nov. 2022 um 12:42 Uhr schrieb Ruperto Camarena <
***@***.***>:

**Comment by acocalypso** [comment]
I joined your discord server. I removed the credentials and I wont connect to your system.

**Comment by acocalypso** [comment]
Discord hierachy was the issue. The role of the bot must be higher than the role you want to manage.
