### ISSUE TITLE
Bot crash after 1min

### ISSUE THREAD

**Issue by vincentdchn** [acocalypso/DiscordRoleManager#6]
Hello, 

I have this error whatever I do with the bot : 

> /home/ubuntu/DiscordRoleManager-master/start.js:109
>                                         bot.createMessage(config.mainChannelID, "⚠ " + rows[rowNumber].temporaryRole + " for user " + member.user.username + " does not exist! Please check your role assignment").catch((err) => { console.log(err) });
>                                                                                                                                              ^
> 
> TypeError: Cannot read property 'user' of undefined
>     at Statement.<anonymous> (/home/ubuntu/DiscordRoleManager-master/start.js:109:107)

And it stops the bot.

**Comment by acocalypso** [comment]
Can you check that you added the serverID in config.json?

"serverID": "7290611111111111"

**Comment by vincentdchn** [comment]
Yes serverID is added

**Comment by acocalypso** [comment]
I setup a new branch with a migration from sqlite to mysql I try to catch such issues as well.

In your case member is undefined. Did you enable SERVER MEMBERS INTENT and PRESENCE INTENT for the bot on discordapp.com?

**Comment by vincentdchn** [comment]
> I setup a new branch with a migration from sqlite to mysql I try to catch such issues as well.

So I need to try again with this new branch ? 

Yup, `SERVER MEMBERS INTENT` & `PRESENCE INTENT` are enabled

**Comment by acocalypso** [comment]
The new branch is wip and not finished yet.

But it will migrate your sqlite data to mysql.

Von: Vincent Duchêne ***@***.***>
Gesendet: Mittwoch, 2. Juni 2021 14:11
An: acocalypso/DiscordRoleManager ***@***.***>
Cc: acocalypso ***@***.***>; Comment ***@***.***>
Betreff: Re: [acocalypso/DiscordRoleManager] Bot crash after 1min (#6)


I setup a new branch with a migration from sqlite to mysql I try to catch such issues as well.

So I need to try again with this new branch ?

Yup, SERVER MEMBERS INTENT & PRESENCE INTENT are enabled

**Comment by vincentdchn** [comment]
Ok thanks !

**Comment by acocalypso** [comment]
You could try the new mysql branch. If you already have a sqlite3 Database the Data will automatically bei converted.

You only need to create a new mysql database.

**Comment by vincentdchn** [comment]
Ok super thank you !

**Comment by vincentdchn** [comment]
It works thank you !
