### ISSUE TITLE
People that check their role will ping all people with the role due the layout of the command.

### ISSUE THREAD

**Issue by Pogodenhelder** [acocalypso/DiscordRoleManager#68]
**Describe the bug**
When a user is doing a test on how long his role will be active bij !tr check @name @role it will ping all the users with that role since you do in a command @role 

**To Reproduce**
1. have a donator role like Vip
2. make a channel where people can do the check command
3. Let people do the command !tr check @name @role 
4. people will get notified that the command is used with that role.

**Expected behavior**
People should not get a ping, but since a user is doing that command to ask the discordbot it will by discord behavior ping all users with that role aswell.

**Screenshots**

**Additional context**
Best would be if its not @role but simply role.

**Comment by acocalypso** [comment]
@Role is no longer required.
You can define a default role in config f.e vip

the command will look like this: 
Personal duration check: ?check 
add new user: ?tr @username 31

**Comment by Pogodenhelder** [comment]
ow wauw. i totally overlooked that part..
