### ISSUE TITLE
ADMIN & MODS commands are accessible to everyone. 

### ISSUE THREAD

**Issue by vincentdchn** [acocalypso/DiscordRoleManager#7]
Hi ! 

I look through the code and tested the bot quit a bit and figured out that mods and admin commands are usable by everyone on the server. 

`config.json` is configured like this : 

>   "adminRoleName": "MODÉRATEUR",
  "modRoleName": "MODÉRATEUR",

`start.js` is set up like this (I didn't touche anything) : 

> 	let AdminR = g.roles.find(role => role.name === config.adminRoleName);
	if (!AdminR) {
		AdminR = { "id": "111111111111111111" };
		console.info("[ERROR] [CONFIG] I could not find admin role: " + config.adminRoleName);
	}
	let ModR = g.roles.find(role => role.name === config.modRoleName);
	if (!ModR) {
		ModR = { "id": "111111111111111111" };
		console.info("[ERROR] [CONFIG] I could not find mod role: " + config.modRoleName);
	}

But still, when a regular member try the command `<temprole add @hisname>`it works ... 

The condition before the command output is : 

> if (g.members.filter(m => m.roles.includes(AdminR.id)) || g.members.filter(m => m.roles.includes(ModR.id)))

Any ideas ?

**Comment by acocalypso** [comment]
Let me debug that, I'll get back to you.

**Comment by vincentdchn** [comment]
Thanks 🙏🏼 It's been 4h and I don't understand why... I'm a beginner btw.

**Comment by acocalypso** [comment]
git pull should fix the issue now.

**Comment by vincentdchn** [comment]
Hey, yeah role permissions works thank you ! 

But now the bot can't reconnect to the database ... 

We agree that I only have to create a new database and then change the infos in the `config.json` right ?

**Comment by acocalypso** [comment]
@vincentdchn just create an empty mysql database and put the information in the config.json.

if you haven't installed the depencies yet, do it now with npm install.
node start.js will start the bot and fill the needed tables for the database and the bot should work.

**Comment by vincentdchn** [comment]
Yay. Everything's working ! Thanks !
